[project]
name = 'Blockchain-Based-Community-Energy-Storage'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.battery-registration]
path = 'contracts/battery-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-optimization]
path = 'contracts/usage-optimization.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
